import type { PoliceOfficeCategory } from '@/models/PoliceOffice';

export type PoliceOfficeSeed = {
    officeKey: string;
    category: PoliceOfficeCategory;
    name: string;
    nameHindi: string;
    address: string;
    addressHindi: string;
    latitude: number;
    longitude: number;
    phone?: string;
    displayOrder: number;
};

/** Default DSP / SDPO / CI offices (new list + previous hardcoded entries). */
export const POLICE_OFFICE_SEED_DATA: PoliceOfficeSeed[] = [
    // —— DSP / SDPO (new) ——
    {
        officeKey: 'dsp_hq',
        category: 'dsp',
        name: 'DSP Headquarter Office',
        nameHindi: 'DSP मुख्यालय कार्यालय',
        address: 'District Police Headquarters, Sadar, Hazaribagh',
        addressHindi: 'जिला पुलिस मुख्यालय, सदर, हजारीबाग',
        latitude: 23.998764,
        longitude: 85.365657,
        displayOrder: 1,
    },
    {
        officeKey: 'dsp_ccr',
        category: 'dsp',
        name: 'DSP CCR Office',
        nameHindi: 'DSP CCR कार्यालय',
        address: 'District Control Room, Sadar, Hazaribagh',
        addressHindi: 'जिला नियंत्रण कक्ष, सदर, हजारीबाग',
        latitude: 23.998764,
        longitude: 85.365657,
        displayOrder: 2,
    },
    {
        officeKey: 'sdpo_sadar',
        category: 'dsp',
        name: 'SDPO Sadar',
        nameHindi: 'SDPO सदर',
        address: 'Sadar, Hazaribagh',
        addressHindi: 'सदर, हजारीबाग',
        latitude: 23.998764,
        longitude: 85.365657,
        displayOrder: 3,
    },
    {
        officeKey: 'sdpo_bishnugarh',
        category: 'dsp',
        name: 'SDPO Bishnugarh',
        nameHindi: 'SDPO बिशुनुगढ़',
        address: 'Bishnugarh, Hazaribagh',
        addressHindi: 'बिशुनुगढ़, हजारीबाग',
        latitude: 23.9139,
        longitude: 85.7753,
        displayOrder: 4,
    },
    {
        officeKey: 'sdpo_barkagaon',
        category: 'dsp',
        name: 'SDPO Barkagaon',
        nameHindi: 'SDPO बरकागाँव',
        address: 'Barkagaon, Hazaribagh',
        addressHindi: 'बरकागाँव, हजारीबाग',
        latitude: 23.6167,
        longitude: 85.4667,
        displayOrder: 5,
    },
    {
        officeKey: 'sdpo_barhi',
        category: 'dsp',
        name: 'SDPO Barhi',
        nameHindi: 'SDPO बरही',
        address: 'Barhi, Hazaribagh',
        addressHindi: 'बरही, हजारीबाग',
        latitude: 24.3,
        longitude: 85.7167,
        displayOrder: 6,
    },
    // —— DSP / SDPO (previous hardcoded) ——
    {
        officeKey: 'dsp_office_sadar',
        category: 'dsp',
        name: 'DSP Office - Sadar',
        nameHindi: 'DSP कार्यालय - सदर',
        address: 'Sadar, Hazaribagh',
        addressHindi: 'सदर, हजारीबाग',
        latitude: 23.9975,
        longitude: 85.3647,
        displayOrder: 7,
    },
    {
        officeKey: 'dsp_office_barkagaon',
        category: 'dsp',
        name: 'DSP Office - Barkagaon',
        nameHindi: 'DSP कार्यालय - बरकागाँव',
        address: 'Barkagaon, Hazaribagh',
        addressHindi: 'बरकागाँव, हजारीबाग',
        latitude: 24.03,
        longitude: 85.38,
        displayOrder: 8,
    },
    {
        officeKey: 'dsp_office_daru',
        category: 'dsp',
        name: 'DSP Office - Daru',
        nameHindi: 'DSP कार्यालय - दारू',
        address: 'Daru, Hazaribagh',
        addressHindi: 'दारू, हजारीबाग',
        latitude: 24.1,
        longitude: 85.42,
        displayOrder: 9,
    },
    // —— CI (new) ——
    {
        officeKey: 'ci_sadar',
        category: 'ci',
        name: 'CI Sadar',
        nameHindi: 'CI सदर',
        address: 'Sadar, Hazaribagh',
        addressHindi: 'सदर, हजारीबाग',
        latitude: 23.998764,
        longitude: 85.365657,
        displayOrder: 1,
    },
    {
        officeKey: 'ci_churchu',
        category: 'ci',
        name: 'CI Churchu',
        nameHindi: 'CI चुरचू',
        address: 'Churchu, Hazaribagh',
        addressHindi: 'चुरचू, हजारीबाग',
        latitude: 23.91,
        longitude: 85.52,
        displayOrder: 2,
    },
    {
        officeKey: 'ci_pelawal',
        category: 'ci',
        name: 'CI Pelawal',
        nameHindi: 'CI पेलावल',
        address: 'Pelawal, Hazaribagh',
        addressHindi: 'पेलावल, हजारीबाग',
        latitude: 23.95,
        longitude: 85.41,
        displayOrder: 3,
    },
    {
        officeKey: 'ci_daru',
        category: 'ci',
        name: 'CI Daru',
        nameHindi: 'CI दारू',
        address: 'Daru, Hazaribagh',
        addressHindi: 'दारू, हजारीबाग',
        latitude: 24.1,
        longitude: 85.42,
        displayOrder: 4,
    },
    {
        officeKey: 'ci_barkagaon',
        category: 'ci',
        name: 'CI Barkagaon',
        nameHindi: 'CI बरकागाँव',
        address: 'Barkagaon, Hazaribagh',
        addressHindi: 'बरकागाँव, हजारीबाग',
        latitude: 23.6167,
        longitude: 85.4667,
        displayOrder: 5,
    },
    {
        officeKey: 'ci_barhi',
        category: 'ci',
        name: 'CI Barhi',
        nameHindi: 'CI बरही',
        address: 'Barhi, Hazaribagh',
        addressHindi: 'बरही, हजारीबाग',
        latitude: 24.3,
        longitude: 85.7167,
        displayOrder: 6,
    },
    {
        officeKey: 'ci_barkatha',
        category: 'ci',
        name: 'CI Barkatha',
        nameHindi: 'CI बरकठा',
        address: 'Barkatha, Hazaribagh',
        addressHindi: 'बरकठा, हजारीबाग',
        latitude: 23.87,
        longitude: 85.58,
        displayOrder: 7,
    },
    // —— CI / Inspector (previous hardcoded) ——
    {
        officeKey: 'insp_office_sadar',
        category: 'ci',
        name: 'Inspector Office - Sadar',
        nameHindi: 'निरीक्षक कार्यालय - सदर',
        address: 'Sadar, Hazaribagh',
        addressHindi: 'सदर, हजारीबाग',
        latitude: 23.998,
        longitude: 85.365,
        displayOrder: 8,
    },
    {
        officeKey: 'insp_office_katkamsandi',
        category: 'ci',
        name: 'Inspector Office - Katkamsandi',
        nameHindi: 'निरीक्षक कार्यालय - कटकमसांडी',
        address: 'Katkamsandi, Hazaribagh',
        addressHindi: 'कटकमसांडी, हजारीबाग',
        latitude: 24.07,
        longitude: 85.39,
        displayOrder: 9,
    },
    {
        officeKey: 'insp_office_churchu',
        category: 'ci',
        name: 'Inspector Office - Churchu',
        nameHindi: 'निरीक्षक कार्यालय - चुरचू',
        address: 'Churchu, Hazaribagh',
        addressHindi: 'चुरचू, हजारीबाग',
        latitude: 23.91,
        longitude: 85.52,
        displayOrder: 10,
    },
];
