/**
 * East Singhbhum / Jamshedpur police stations & outposts.
 * Source: public/East_Singhbhum_Police_Directory (1).pdf
 * (Hindi officers PDF is image-scanned — Hindi names filled from standard place names.)
 *
 * displayOrder: 1 = P.S., 2 = O.P., 3 = Traffic / specialty units (directory only)
 * Coordinates: OSM / public listings where available; otherwise locality approx for nearest-GPS.
 */
export type PoliceStationSeed = {
    name: string;
    nameHindi: string;
    address: string;
    addressHindi: string;
    latitude: number;
    longitude: number;
    governmentNumber: string;
    personalNumber?: string;
    inchargeName?: string;
    inchargeNameHindi?: string;
    displayOrder: number;
    showInAssociatedPsList?: boolean;
};

const D = 'East Singhbhum';

export const POLICE_STATION_SEED_DATA: PoliceStationSeed[] = [
    // ─── City / Jamshedpur P.S. ─────────────────────────────────────────────
    {
        name: 'Sitaramdera P.S.',
        nameHindi: 'सीतारामडेरा थाना',
        address: `Sitaramdera, Jamshedpur, ${D}, Jharkhand`,
        addressHindi: 'सीतारामडेरा, जमशेदपुर, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.835, longitude: 86.205,
        governmentNumber: '9431706509',
        inchargeName: 'Inspector Anand Kumar Mishra',
        displayOrder: 1,
    },
    {
        name: 'Sidhgora P.S.',
        nameHindi: 'सिद्धगोड़ा थाना',
        address: `Sidhgora, Jamshedpur, ${D}, Jharkhand`,
        addressHindi: 'सिद्धगोड़ा, जमशेदपुर, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.7989389, longitude: 86.2302396,
        governmentNumber: '9431706508',
        inchargeName: 'Inspector Faiz Ahmed',
        displayOrder: 1,
    },
    {
        name: 'Mango P.S.',
        nameHindi: 'मानगो थाना',
        address: `Purulia Road, Mango, Jamshedpur, ${D}, Jharkhand 831012`,
        addressHindi: 'पुरुलिया रोड, मानगो, जमशेदपुर, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.8290635, longitude: 86.2112725,
        governmentNumber: '9431706488',
        inchargeName: 'Inspector Nityanand Prasad',
        displayOrder: 1,
    },
    {
        name: 'Kadma P.S.',
        nameHindi: 'कडमा थाना',
        address: `Kadma, Jamshedpur, ${D}, Jharkhand`,
        addressHindi: 'कडमा, जमशेदपुर, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.7983337, longitude: 86.1723886,
        governmentNumber: '9431706506',
        inchargeName: 'Inspector Dilip Kumar Yadav',
        displayOrder: 1,
    },
    {
        name: 'Sonari P.S.',
        nameHindi: 'सोनारी थाना',
        address: `Sonari, Jamshedpur, ${D}, Jharkhand`,
        addressHindi: 'सोनारी, जमशेदपुर, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.8102404, longitude: 86.172299,
        governmentNumber: '9431706507',
        inchargeName: 'Inspector Madhusudan Dey',
        displayOrder: 1,
    },
    {
        name: 'Sakchi P.S.',
        nameHindi: 'साकची थाना',
        address: `Ambagan, Sakchi, Jamshedpur, ${D}, Jharkhand 831001`,
        addressHindi: 'अम्बागान, साकची, जमशेदपुर, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.8019239, longitude: 86.1998071,
        governmentNumber: '9431706491',
        inchargeName: 'Inspector Gopal Krishna Yadav',
        displayOrder: 1,
    },
    {
        name: 'Telco P.S.',
        nameHindi: 'टेल्को थाना',
        address: `Telco Colony, Jamshedpur, ${D}, Jharkhand 831004`,
        addressHindi: 'टेल्को कॉलोनी, जमशेदपुर, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.7683839, longitude: 86.2558816,
        governmentNumber: '9431706510',
        inchargeName: 'Inspector Suresh Prasad',
        displayOrder: 1,
    },
    {
        name: 'Golmuri P.S.',
        nameHindi: 'गोलमुरी थाना',
        address: `Golmuri, Jamshedpur, ${D}, Jharkhand 831009`,
        addressHindi: 'गोलमुरी, जमशेदपुर, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.7829567, longitude: 86.2274976,
        governmentNumber: '9431706494',
        inchargeName: 'Inspector Sanjay Suman',
        displayOrder: 1,
    },
    {
        name: 'Burma Mines P.S.',
        nameHindi: 'बर्मा माइंस थाना',
        address: `Burma Mines, Jamshedpur, ${D}, Jharkhand`,
        addressHindi: 'बर्मा माइंस, जमशेदपुर, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.795, longitude: 86.225,
        governmentNumber: '9431706513',
        inchargeName: 'Inspector Kumar Saryu Anand',
        displayOrder: 1,
    },
    {
        name: 'Govindpur P.S.',
        nameHindi: 'गोविंदपुर थाना',
        address: `Govindpur, Jamshedpur, ${D}, Jharkhand`,
        addressHindi: 'गोविंदपुर, जमशेदपुर, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.742798, longitude: 86.260725,
        governmentNumber: '9431706511',
        inchargeName: 'Sub-Inspector Pawan Kumar',
        displayOrder: 1,
    },
    {
        name: 'Birsanagar P.S.',
        nameHindi: 'बिरसानगर थाना',
        address: `Birsanagar, Jamshedpur, ${D}, Jharkhand`,
        addressHindi: 'बिरसानगर, जमशेदपुर, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.805, longitude: 86.245,
        governmentNumber: '9431706512',
        personalNumber: '8986601484',
        inchargeName: 'Sub-Inspector Santosh Kumar',
        displayOrder: 1,
    },
    {
        name: 'Jugsalai P.S.',
        nameHindi: 'जुगसलाई थाना',
        address: `Millennium Park area, Jugsalai, Jamshedpur, ${D}, Jharkhand 831002`,
        addressHindi: 'मिलेनियम पार्क क्षेत्र, जुगसलाई, जमशेदपुर, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.7826968, longitude: 86.1847328,
        governmentNumber: '9431706495',
        inchargeName: 'Inspector Ghulam Rabbani Khan',
        displayOrder: 1,
    },
    {
        name: 'Parsudih P.S.',
        nameHindi: 'परसुडीह थाना',
        address: `Parsudih, Jamshedpur, ${D}, Jharkhand`,
        addressHindi: 'परसुडीह, जमशेदपुर, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.7556816, longitude: 86.2154572,
        governmentNumber: '9431706515',
        inchargeName: 'Inspector Avinash Kumar',
        displayOrder: 1,
    },
    {
        name: 'Bagbera P.S.',
        nameHindi: 'बागबेड़ा थाना',
        address: `Bagbera, Jamshedpur, ${D}, Jharkhand`,
        addressHindi: 'बागबेड़ा, जमशेदपुर, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.748, longitude: 86.175,
        governmentNumber: '9431706514',
        inchargeName: 'Inspector Umesh Kumar Thakur',
        displayOrder: 1,
    },
    {
        name: 'Sundarnagar P.S.',
        nameHindi: 'सुंदरनगर थाना',
        address: `Sundarnagar, Jamshedpur, ${D}, Jharkhand`,
        addressHindi: 'सुंदरनगर, जमशेदपुर, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.77, longitude: 86.205,
        governmentNumber: '9431706516',
        inchargeName: 'Sub-Inspector Ajit Kumar Munda',
        displayOrder: 1,
    },
    {
        name: 'Bistupur P.S.',
        nameHindi: 'बिस्तुपुर थाना',
        address: `Bistupur Main Road, Regal Chowk, Bistupur, Jamshedpur, ${D}, Jharkhand 831001`,
        addressHindi: 'बिस्तुपुर मेन रोड, रीगल चौक, बिस्तुपुर, जमशेदपुर, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.7883785, longitude: 86.1851675,
        governmentNumber: '9431706497',
        inchargeName: 'Inspector Niranjan Kumar',
        displayOrder: 1,
    },
    {
        name: 'MGM P.S.',
        nameHindi: 'एमजीएम थाना',
        address: `MGM area, Dimna / Mango, Jamshedpur, ${D}, Jharkhand`,
        addressHindi: 'एमजीएम क्षेत्र, डिमना / मानगो, जमशेदपुर, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.8434993, longitude: 86.2311662,
        governmentNumber: '9431706503',
        inchargeName: 'Inspector Sachin Kumar Das',
        displayOrder: 1,
    },
    {
        name: 'Azadnagar P.S.',
        nameHindi: 'आज़ादनगर थाना',
        address: `Azadnagar, Jamshedpur, ${D}, Jharkhand`,
        addressHindi: 'आज़ादनगर, जमशेदपुर, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.812, longitude: 86.218,
        governmentNumber: '9431706502',
        inchargeName: 'Inspector Chandan Kumar',
        displayOrder: 1,
    },

    // ─── Specialty P.S. ─────────────────────────────────────────────────────
    {
        name: 'Women & Child Protection P.S. Sakchi',
        nameHindi: 'महिला एवं बाल संरक्षण थाना, साकची',
        address: `Sakchi, Jamshedpur, ${D}, Jharkhand`,
        addressHindi: 'साकची, जमशेदपुर, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.8025, longitude: 86.2005,
        governmentNumber: '9939244244',
        inchargeName: 'W/Sub-Inspector Rupa Pal',
        displayOrder: 1,
        showInAssociatedPsList: true,
    },
    {
        name: 'Cyber P.S. Bistupur',
        nameHindi: 'साइबर थाना, बिस्तुपुर',
        address: `Bistupur, Jamshedpur, ${D}, Jharkhand`,
        addressHindi: 'बिस्तुपुर, जमशेदपुर, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.789, longitude: 86.1855,
        governmentNumber: '9430774631',
        inchargeName: 'Inspector Srinivas',
        displayOrder: 1,
    },
    {
        name: 'Women & Child Protection P.S. Ghatshila',
        nameHindi: 'महिला एवं बाल संरक्षण थाना, घाटशिला',
        address: `Ghatshila, ${D}, Jharkhand (Additional: AHTU Jamshedpur)`,
        addressHindi: 'घाटशिला, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.666, longitude: 86.508,
        governmentNumber: '8986601421',
        inchargeName: 'W/Sub-Inspector Manjushree Kukul',
        displayOrder: 1,
    },

    // ─── Rural / subdivision P.S. ───────────────────────────────────────────
    {
        name: 'Ghatshila P.S.',
        nameHindi: 'घाटशिला थाना',
        address: `Ghatshila, ${D}, Jharkhand`,
        addressHindi: 'घाटशिला, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.6650418, longitude: 86.507034,
        governmentNumber: '9431706517',
        inchargeName: 'Inspector Rajendra Kumar Munda',
        displayOrder: 1,
    },
    {
        name: 'Galudih P.S.',
        nameHindi: 'गालूडीह थाना',
        address: `Galudih, ${D}, Jharkhand`,
        addressHindi: 'गालूडीह, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.6480073, longitude: 86.4115668,
        governmentNumber: '9430774620',
        inchargeName: 'Sub-Inspector Anku Kumar',
        displayOrder: 1,
    },
    {
        name: 'Shyamsundarpur P.S.',
        nameHindi: 'श्यामसुंदरपुर थाना',
        address: `Shyamsundarpur, ${D}, Jharkhand`,
        addressHindi: 'श्यामसुंदरपुर, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.35, longitude: 86.72,
        governmentNumber: '9431706521',
        inchargeName: 'Sub-Inspector Sunil Kumar Bhokta',
        displayOrder: 1,
    },
    {
        name: 'Baharagora P.S.',
        nameHindi: 'बहरागोड़ा थाना',
        address: `Baharagora, ${D}, Jharkhand 832101`,
        addressHindi: 'बहरागोड़ा, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.3162862, longitude: 86.7539176,
        governmentNumber: '9431706526',
        inchargeName: 'Sub-Inspector Shankar Pr. Kushwaha',
        displayOrder: 1,
    },
    {
        name: 'Chakulia P.S.',
        nameHindi: 'चाकुलिया थाना',
        address: `Chakulia, ${D}, Jharkhand`,
        addressHindi: 'चाकुलिया, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.4728207, longitude: 86.6763429,
        governmentNumber: '9431706520',
        inchargeName: 'Sub-Inspector Rajesh Kumar',
        displayOrder: 1,
    },
    {
        name: 'Barsol P.S.',
        nameHindi: 'बरसोल थाना',
        address: `Barsol, ${D}, Jharkhand`,
        addressHindi: 'बरसोल, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.34, longitude: 86.7,
        governmentNumber: '9431706527',
        inchargeName: 'Sub-Inspector Abhishek Kumar',
        displayOrder: 1,
    },
    {
        name: 'Dhalbhumgarh P.S.',
        nameHindi: 'धालभूमगढ़ थाना',
        address: `Dhalbhumgarh, ${D}, Jharkhand 832302`,
        addressHindi: 'धालभूमगढ़, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.5174333, longitude: 86.5439256,
        governmentNumber: '9431706519',
        inchargeName: 'Sub-Inspector Dheeraj Kumar Mishra',
        displayOrder: 1,
    },
    {
        name: 'Patamda P.S.',
        nameHindi: 'पतमड़ा थाना',
        address: `Patamda, ${D}, Jharkhand`,
        addressHindi: 'पतमड़ा, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.8951218, longitude: 86.3864397,
        governmentNumber: '9431706504',
        inchargeName: 'Sub-Inspector Vishnu Charan Bhokta',
        displayOrder: 1,
    },
    {
        name: 'Kamalpur P.S.',
        nameHindi: 'कमलपुर थाना',
        address: `Kamalpur, ${D}, Jharkhand`,
        addressHindi: 'कमलपुर, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.91, longitude: 86.35,
        governmentNumber: '9431706505',
        inchargeName: 'Sub-Inspector Ashok Kumar',
        displayOrder: 1,
    },
    {
        name: 'Bodam P.S.',
        nameHindi: 'बोदाम थाना',
        address: `Bodam, ${D}, Jharkhand`,
        addressHindi: 'बोदाम, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.88, longitude: 86.42,
        governmentNumber: '9430774617',
        inchargeName: 'Sub-Inspector Neeraj Kumar',
        displayOrder: 1,
    },
    {
        name: 'Gudabanda P.S.',
        nameHindi: 'गुड़ाबांदा थाना',
        address: `Gudabanda, ${D}, Jharkhand`,
        addressHindi: 'गुड़ाबांदा, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.45, longitude: 86.55,
        governmentNumber: '9431706528',
        inchargeName: 'Sub-Inspector Kumar Sumit Yadav',
        displayOrder: 1,
    },
    {
        name: 'Jadugora P.S.',
        nameHindi: 'जादूगोड़ा थाना',
        address: `Jadugora (Jaduguda), ${D}, Jharkhand 832102`,
        addressHindi: 'जादूगोड़ा, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.6556344, longitude: 86.349953,
        governmentNumber: '9431706523',
        inchargeName: 'Sub-Inspector Ishwar Dayal Munda',
        displayOrder: 1,
    },
    {
        name: 'Musabani P.S.',
        nameHindi: 'मुसाबनी थाना',
        address: `Musabani, ${D}, Jharkhand`,
        addressHindi: 'मुसाबनी, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.5586862, longitude: 86.409668,
        governmentNumber: '9431706522',
        inchargeName: 'Sub-Inspector Anuj Kumar Singh',
        displayOrder: 1,
    },
    {
        name: 'Potka P.S.',
        nameHindi: 'पोटका थाना',
        address: `Potka, ${D}, Jharkhand`,
        addressHindi: 'पोटका, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.5910615, longitude: 86.2309635,
        governmentNumber: '9431706525',
        inchargeName: 'Sub-Inspector Sunny Toppo',
        displayOrder: 1,
    },
    {
        name: 'Kowali P.S.',
        nameHindi: 'कोवाली थाना',
        address: `Kowali (Kuyali), Potka, ${D}, Jharkhand`,
        addressHindi: 'कोवाली, पोटका, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.5076013, longitude: 86.1847186,
        governmentNumber: '9430774639',
        inchargeName: 'Sub-Inspector Mukesh Kumar Saw',
        displayOrder: 1,
    },
    {
        name: 'Dumaria P.S.',
        nameHindi: 'डुमरिया थाना',
        address: `Dumaria, ${D}, Jharkhand`,
        addressHindi: 'डुमरिया, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.415829, longitude: 86.4078292,
        governmentNumber: '9431706524',
        inchargeName: 'Sub-Inspector Pancham Tigga',
        displayOrder: 1,
    },

    // ─── Outposts ───────────────────────────────────────────────────────────
    {
        name: 'Moubhandar O.P.',
        nameHindi: 'मौभंडार चौकी',
        address: `Moubhandar, near Ghatshila, ${D}, Jharkhand`,
        addressHindi: 'मौभंडार, घाटशिला के पास, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.65, longitude: 86.49,
        governmentNumber: '9431706518',
        inchargeName: 'Sub-Inspector Neeraj Kumar Gupta',
        displayOrder: 2,
    },
    {
        name: 'Olidih O.P.',
        nameHindi: 'ओलीडीह चौकी',
        address: `Olidih, Jamshedpur, ${D}, Jharkhand`,
        addressHindi: 'ओलीडीह, जमशेदपुर, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.82, longitude: 86.215,
        governmentNumber: '9431706501',
        inchargeName: 'Sub-Inspector Md. Sharik Ali',
        displayOrder: 2,
    },

    // ─── Traffic units (directory / alerts; excluded from nearest GPS) ──────
    {
        name: 'Sakchi Traffic',
        nameHindi: 'साकची ट्रैफिक',
        address: `Sakchi, Jamshedpur, ${D}, Jharkhand`,
        addressHindi: 'साकची, जमशेदपुर, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.8019, longitude: 86.1998,
        governmentNumber: '9430774659',
        inchargeName: 'Inspector Shankar Kumar',
        displayOrder: 3,
        showInAssociatedPsList: false,
    },
    {
        name: 'Bistupur Traffic',
        nameHindi: 'बिस्तुपुर ट्रैफिक',
        address: `Bistupur, Jamshedpur, ${D}, Jharkhand`,
        addressHindi: 'बिस्तुपुर, जमशेदपुर, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.7884, longitude: 86.1852,
        governmentNumber: '9430774644',
        inchargeName: 'Inspector Rakesh Kumar Singh',
        displayOrder: 3,
        showInAssociatedPsList: false,
    },
    {
        name: 'Jugsalai Traffic',
        nameHindi: 'जुगसलाई ट्रैफिक',
        address: `Jugsalai, Jamshedpur, ${D}, Jharkhand`,
        addressHindi: 'जुगसलाई, जमशेदपुर, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.7827, longitude: 86.1847,
        governmentNumber: '9430774653',
        inchargeName: 'Inspector Sanjay Janak Murti',
        displayOrder: 3,
        showInAssociatedPsList: false,
    },
    {
        name: 'Golmuri Traffic',
        nameHindi: 'गोलमुरी ट्रैफिक',
        address: `Golmuri, Jamshedpur, ${D}, Jharkhand`,
        addressHindi: 'गोलमुरी, जमशेदपुर, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.783, longitude: 86.2275,
        governmentNumber: '9430774649',
        inchargeName: 'Inspector Md. Quddus',
        displayOrder: 3,
        showInAssociatedPsList: false,
    },
    {
        name: 'Mango Traffic',
        nameHindi: 'मानगो ट्रैफिक',
        address: `Mango, Jamshedpur, ${D}, Jharkhand`,
        addressHindi: 'मानगो, जमशेदपुर, पूर्वी सिंहभूम, झारखण्ड',
        latitude: 22.8291, longitude: 86.2113,
        governmentNumber: '9430774641',
        inchargeName: 'Inspector Hariodh Karmali',
        displayOrder: 3,
        showInAssociatedPsList: false,
    },
];
